### ISSUE TITLE
TODO 2017/10/09

### ISSUE THREAD

**Issue by yihui** [rbind/yihui#24]
- [x] What to do with `knitr:::wrap()`: https://github.com/yihui/knitr/issues/1442 should I rename it before exporting it?
- [x] Figure out a _reasonable_ plan for the [rmarkdown 1.17](https://github.com/rstudio/rmarkdown/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.7) release.
- [x] A letter for Brooke.
